name: Build and Deploy

on:
  push:
    branches:
      - 'preview'
      - 'versions/3.0-complete'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BASE_URL: https://dev.nightwatchjs.org
      REMOTE_SERVER: ${{ secrets.REMOTE_SERVER }}
      REMOTE_USER: ${{ secrets.REMOTE_USER }}
      API_DOCS_FOLDER: ${{ github.workspace }}/nightwatch/lib/api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout Nightwatch source code
        uses: actions/checkout@v2
        with:
          repository: nightwatchjs/nightwatch
          path: nightwatch

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the website
        run: npm run build

      - name: Creating symlinks to old version
        run: |
          ln -s ../nightwatchjs.org out/v17
          ln -s ../v09.nightwatchjs.org out/v09
          ln -s ../nightwatch-v26 out/v26

      - name: Deploy to server
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PROD_DEPLOY_SECRET }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ env.REMOTE_SERVER }} >> ~/.ssh/known_hosts
          rsync -azP --delete ./out/ ${{ env.REMOTE_USER }}@${{ env.REMOTE_SERVER }}:${{ secrets.REMOTE_PREVIEW_DIRECTORY }}